const events = {
  CREATE_RULE_CONFIG: 'CREATE_RULE_CONFIG',
  UPDATE_PROXY_SERVER_LOG_COUNT: 'UPDATE_PROXY_SERVER_LOG_COUNT',
  CLEAR_RECORDS: 'CLEAR_RECORDS',
  ADD_REQUEST: 'ADD_REQUEST',
  REMOVE_REQUEST: 'REMOVE_REQUEST'
}

export default events
