const events = {
  CREATE_RULE_CONFIG: 'CREATE_RULE_CONFIG',
  UPDATE_PROXY_SERVER_LOG_COUNT: 'UPDATE_PROXY_SERVER_LOG_COUNT',
  CLEAR_RECORDS: 'CLEAR_RECORDS',
  ADD_REQUEST: 'ADD_REQUEST',
  REMOVE_REQUEST: 'REMOVE_REQUEST',
  UPDATE_HITTED_RULE_COUNT: 'UPDATE_HITTED_RULE_COUNT',
  UPDATE_REQUEST_LIST_COUNT: 'UPDATE_REQUEST_LIST_COUNT',
  FILTER_RECORD: 'FILTER_RECORD'
}

export default events
